# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
        environment:
          PROJECT_NAME: circleci-go
          IMAGE_NAME: exfly/container
    steps:
      - checkout
      - setup_remote_docker  
      - run:
          name: Build Docker image
          command: |
            docker build -t "$IMAGE_NAME" .
